version: '3.2'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=vale
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=base

#  redis:
#    restart: on-failure
#    image: redis:6.0.10
#    ports:
#    - 6379:6379

volumes:
  postgres_data:
